### ISSUE TITLE
Issuing server commands is cumbersome

### ISSUE THREAD

**Issue by Laura7089** [FragSoc/barotrauma-docker#2]
Issuing commands directly to the server requires enabling tty mode or running interactively, neither of these are good options.

Perhaps an rcon client?

**Comment by mygamingaccount** [comment]
I used TMUX with good results for running BT, but it has issues once the docker client/server connection gets in the way.

It's for good for a one-time setup, after which you turn off the TTY/STDIN, or manage the server by editing the xml files

**Comment by Laura7089** [comment]
I don't think there's any solution to this that beats just attaching a tty + making interactive, effort-wise.
