### ISSUE TITLE
Config file missing

### ISSUE THREAD

**Issue by Laura7089** [FragSoc/barotrauma-docker#4]
`./player_config.xml` is not synced to the configuration directory

**Comment by mygamingaccount** [comment]
Have you tried bind-mounting the files?
I use docker-compose only for convenience. Take a look at my take on the issue:

https://github.com/mygamingaccount/barotrauma_docker_dedicated/blob/master/docker-compose.yml

I haven't done the mod-downloading part

**Comment by Laura7089** [comment]
I think it's a typo in the `Dockerfile` causing this - I prefer to keep all the config files in one folder on their own so that end users can, as you say, just bind mount that folder instead of having to faff about with `touch`ing config files and then mounting them all the correct places (though this approach will also work with this image).

**Comment by Laura7089** [comment]
Turns out I was looking for the wrong file - `config_player.xml` is synced fine, `player_config.xml` does not exist...
